name: Delete Resources from AWS
on:
  workflow_dispatch:


jobs:
  plan:
    name: Terraform Destroy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Initialise project and view terraform plan
        # run: |
        #   terraform fmt
        #   terraform init
        #   terraform plan -destroy 
        #   terraform destroy -auto-approve
        run: |
          terraform fmt
          terraform init
          terraform plan -destroy -out=destroy.tfplan
          terraform apply destroy.tfplan